// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIUc3647qHNyuhQOynvxuSWHDn2HsfQe0',
    appId: '1:565562719302:web:c5196f00d042049d915e47',
    messagingSenderId: '565562719302',
    projectId: 'pushnotification-5ae02',
    authDomain: 'pushnotification-5ae02.firebaseapp.com',
    storageBucket: 'pushnotification-5ae02.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBq1gnd7XybupuznK5SRNc6RvCC0taL-7k',
    appId: '1:565562719302:android:14f1fb48a751ce1e915e47',
    messagingSenderId: '565562719302',
    projectId: 'pushnotification-5ae02',
    storageBucket: 'pushnotification-5ae02.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAk1iptDULVi2MF8o3ppQhuAu7oAvAGfw',
    appId: '1:565562719302:ios:1e7244a02e575513915e47',
    messagingSenderId: '565562719302',
    projectId: 'pushnotification-5ae02',
    storageBucket: 'pushnotification-5ae02.firebasestorage.app',
    iosBundleId: 'com.example.pushnotification',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAk1iptDULVi2MF8o3ppQhuAu7oAvAGfw',
    appId: '1:565562719302:ios:1e7244a02e575513915e47',
    messagingSenderId: '565562719302',
    projectId: 'pushnotification-5ae02',
    storageBucket: 'pushnotification-5ae02.firebasestorage.app',
    iosBundleId: 'com.example.pushnotification',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCIUc3647qHNyuhQOynvxuSWHDn2HsfQe0',
    appId: '1:565562719302:web:28a0aad520c8825c915e47',
    messagingSenderId: '565562719302',
    projectId: 'pushnotification-5ae02',
    authDomain: 'pushnotification-5ae02.firebaseapp.com',
    storageBucket: 'pushnotification-5ae02.firebasestorage.app',
  );
}
